-- 1 + 2
drop schema GESTION;

create schema GESTION;

use GESTION;

CREATE TABLE CLIENTES (
    CLIENTE INT,
    EMPRESA VARCHAR(20) NOT NULL,
    COMERCIAL INT,
    LIM_CREDITO DECIMAL(5, 2),
    CONSTRAINT pk_Cli PRIMARY KEY (CLIENTE),
    CONSTRAINT ck_limCredit check (
        LIM_CREDITO BETWEEN 0 AND 3000
    )
);

CREATE TABLE PRODUCTOS (
    ID_FABRICA VARCHAR(3),
    PRODUCTO VARCHAR(5),
    DESCRIPCION VARCHAR(20),
    PRECIO DECIMAL(5, 2) NOT NULL,
    EXISTENCIAS INT NOT NULL,
    CONSTRAINT pk_Prod PRIMARY KEY (ID_FABRICA, PRODUCTO)
);

CREATE TABLE OFICINAS (
    OFICINA INT,
    CIUDAD VARCHAR(15) DEFAULT 'GIJON',
    DIRECTOR INT,
    REGION VARCHAR(10),
    OBJETIVOS DECIMAL(6, 2),
    VENTAS DECIMAL(6, 2),
    CONSTRAINT pk_Ofi PRIMARY KEY (OFICINA)
);

CREATE TABLE COMERCIALES (
    COMERCIAL INT,
    NOMBRE VARCHAR(15),
    EDAD INT,
    OFICINA INT,
    CARGO VARCHAR(10),
    CONTRATO DATE,
    DIRECTOR INT,
    CUOTA DECIMAL(5, 2),
    VENTAS DECIMAL(5, 2),
    CONSTRAINT pk_Com PRIMARY KEY (COMERCIAL),
    CONSTRAINT pk_OfiCom FOREIGN KEY (OFICINA) REFERENCES OFICINAS (OFICINA)
);

CREATE TABLE PEDIDOS (
    PEDIDO INT,
    FECHA DATE,
    CLIENTE INT,
    COMERCIAL INT,
    ID_FABRICA VARCHAR(3),
    PRODUCTO VARCHAR(5) NOT NULL,
    CANTIDAD INT NOT NULL,
    IMPORTE DECIMAL(5, 2) NOT NULL,
    CONSTRAINT pk_Ped PRIMARY KEY (PEDIDO),
    CONSTRAINT fk_ProdPed FOREIGN KEY (ID_FABRICA, PRODUCTO) REFERENCES PRODUCTOS (ID_FABRICA, PRODUCTO),
    CONSTRAINT fk_CliPed FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CLIENTE),
    CONSTRAINT fk_ComPed FOREIGN KEY (COMERCIAL) REFERENCES COMERCIALES (COMERCIAL)
);

-- 3
ALTER TABLE OFICINAS RENAME TO SUCURSALES;

-- RENAME TABLE OFICINAS TO SUCURSALES;
-- 4
ALTER TABLE COMERCIALES
ADD APELLIDO1 VARCHAR(50),
ADD APELLIDO2 VARCHAR(50);

-- 5
ALTER TABLE SUCURSALES MODIFY DIRECTOR VARCHAR(15);

-- 6
ALTER TABLE COMERCIALES CHANGE COLUMN CARGO PUESTO VARCHAR(10);

-- 7
CREATE TABLE FABRICA (
    Cod_Fabrica INT,
    NOMBRE VARCHAR(25),
    CIUDAD VARCHAR(15),
    CONSTRAINT ck_ProdFab FOREIGN KEY (Cod_Fabrica) REFERENCES PRODUCTOS (ID_FABRICA)
);

-- 8
ALTER TABLE PEDIDOS
DROP FOREIGN KEY ID_FABRICA,
DROP FOREIGN KEY PRODUCTO;

-- 9
CREATE USER 'Rodrigo' @'%' IDENTIFIED BY 'Rodrigo';

DROP USER 'Rodrigo' @'%';